#!/usr/bin/env ruby

require_relative 'lib/console'

def console_help
  puts <<HELP
Commands
--------

--update {SITE}   Updates the current site. Calls the same code as the web application, except it does not send a payload.
--restore {SITE}  Restores the site to the last backup (if one exists).
--help            Shows this help menu.

Examples
--------
console --update myproj
console --restore myproj

HELP
end

if __FILE__ == $0
  puts <<HEAD
*----------------*
| Ripple Console |
*----------------*

HEAD

  unless ARGV.empty?
    args    = ARGV.dup
    command = args.shift

    console = Ripple::Console.new args
    case command
    when '--update'
      console.update
    when '--restore'
      console.restore
    when '--self-update'
      console.self_update
    when '--help'
      console_help
    else
      stop 'Whatcha doing? Use --help for advice.'
    end

    exit
  end

  console_help
end